name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ] # Run on all branches for PRs

jobs:
  lint-test-build:
    name: Lint, Test, and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn' # Cache Yarn dependencies

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linters
        run: yarn lint # Assumes root package.json has a lint script running workspace lints

      - name: Run tests
        run: yarn test # Assumes root package.json has a test script running workspace tests

      - name: Build backend
        run: yarn build:backend # Assumes root package.json script: "yarn workspace backend build"

      - name: Build frontend
        run: yarn build:frontend # Assumes root package.json script: "yarn workspace frontend build"

  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: lint-test-build # Ensure lint, test, and build pass before deploying
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    permissions: # Needed for Workload Identity Federation
      contents: 'read'
      id-token: 'write'

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      FRONTEND_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend
      BACKEND_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend
      GCP_REGION: europe-west1 # Set region to europe-west1
      TERRAFORM_DIR: ./terraform # Assuming terraform files are in a 'terraform' directory at the root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud via Workload Identity Federation
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }} # e.g. projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }} # e.g. my-service-account@my-project.iam.gserviceaccount.com

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        # with:
        #   terraform_version: "1.0.0" # Optional: specify Terraform version

      - name: Terraform Init
        run: terraform -chdir=${{ env.TERRAFORM_DIR }} init

      - name: Terraform Validate
        run: terraform -chdir=${{ env.TERRAFORM_DIR }} validate

      - name: Terraform Plan
        run: terraform -chdir=${{ env.TERRAFORM_DIR }} plan -out=tfplan
        env:
          TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_gcp_region: ${{ env.GCP_REGION }}
          TF_VAR_frontend_image_name: ${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}
          TF_VAR_backend_image_name: ${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }}
          # Add other TF_VAR_ variables as needed from your variables.tf, e.g.
          # TF_VAR_db_instance_name: "bjj-academy-db-instance" # If not using random suffix or want to control via CI
          # TF_VAR_db_name: "bjj-academy-db"
          # TF_VAR_db_user_name: "bjj-academy-iam-user"


      # Build and Push Docker Images (before Terraform Apply)
      - name: Build Frontend Docker image
        run: docker build -t ${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }} -f frontend/Dockerfile ./frontend

      - name: Push Frontend Docker image to GCR
        run: docker push ${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}

      - name: Build Backend Docker image
        run: docker build -t ${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }} -f backend/Dockerfile ./backend

      - name: Push Backend Docker image to GCR
        run: docker push ${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }}

      - name: Terraform Apply
        run: terraform -chdir=${{ env.TERRAFORM_DIR }} apply -auto-approve tfplan
